version: '3'

services:
  voronoi-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/voronoi-pypy:0.4.0
    volumes:
      - ./pyproject.toml:/opt/voronoi/pyproject.toml
      - ./README.md:/opt/voronoi/README.md
      - ./setup.py:/opt/voronoi/setup.py
      - ./tests:/opt/voronoi/tests
      - ./voronoi:/opt/voronoi/voronoi
    entrypoint: pytest
