version: '3'

services:
  voronoi-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/voronoi-cpython:0.3.1
    volumes:
      - ./pyproject.toml:/opt/voronoi/pyproject.toml
      - ./README.md:/opt/voronoi/README.md
      - ./setup.py:/opt/voronoi/setup.py
      - ./src:/opt/voronoi/src
      - ./tests:/opt/voronoi/tests
      - ./voronoi:/opt/voronoi/voronoi
    entrypoint: pytest
