version: '3'

services:
  voronoi-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/voronoi-pypy:0.3.1-alpha
    volumes:
      - ./voronoi/:/opt/voronoi/voronoi/
      - ./pytest.ini:/opt/voronoi/pytest.ini
      - ./README.md:/opt/voronoi/README.md
      - ./requirements-setup.txt:/opt/voronoi/requirements-setup.txt
      - ./requirements-tests.txt:/opt/voronoi/requirements-tests.txt
      - ./requirements.txt:/opt/voronoi/requirements.txt
      - ./setup.py:/opt/voronoi/setup.py
      - ./tests/:/opt/voronoi/tests/
    entrypoint: pytest
